<?php
/**
 * TL_ROOT/system/modules/downloadarchive/languages/ja/default.php 
 * 
 * Contao extension: downloadarchive 2.0.0 stable 
 * Japanese translation file 
 * 
 * Copyright : &copy; 2008 - 2012 Felix Pfeiffer - Neue Medien 
 * License   : LGPL 
 * Author    : Felix Pfeiffer (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['keinDownload'] = "ファイルがみつかりません";
$GLOBALS['TL_LANG']['CTE']['downloadarchiv']['0'] = "ダウンロードアーカイブ";
$GLOBALS['TL_LANG']['CTE']['downloadarchiv']['1'] = "コンテンツ要素としてダウンロードアーカイブを選択します。";
 
?>
