<?php
/**
 * TL_ROOT/system/modules/downloadarchive/languages/ja/modules.php 
 * 
 * Contao extension: downloadarchive 2.0.0 stable 
 * Japanese translation file 
 * 
 * Copyright : &copy; 2008 - 2012 Felix Pfeiffer - Neue Medien 
 * License   : LGPL 
 * Author    : Felix Pfeiffer (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['downloadarchiv']['0'] = "ダウンロードアーカイブ";
$GLOBALS['TL_LANG']['MOD']['downloadarchiv']['1'] = "ダウンロードアーカイブは1つ以上のフォルダーからファイルのダウンロードと、meta.txtに関係なく適切な題名と説明を各ファイルに提供を可能とします。さらに、各ファイルにダウンロードの許可を設定できます。";
$GLOBALS['TL_LANG']['FMD']['downloadarchive']['0'] = "ダウンロードアーカイブ";
$GLOBALS['TL_LANG']['FMD']['downloadarchive']['1'] = "このモジュールはダウンロードアーカイブでファイルを提供します。";
 
?>
