<?php
/**
 * TL_ROOT/system/modules/downloadarchive/languages/ja/tl_content.php 
 * 
 * Contao extension: downloadarchive 2.0.0 stable 
 * Japanese translation file 
 * 
 * Copyright : &copy; 2008 - 2012 Felix Pfeiffer - Neue Medien 
 * License   : LGPL 
 * Author    : Felix Pfeiffer (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['downloadarchiv']['0'] = "ダウンロードアーカイブ";
$GLOBALS['TL_LANG']['tl_content']['downloadarchiv']['1'] = "ダウンロードアーカイブを選択してください。";
$GLOBALS['TL_LANG']['tl_content']['downloadShowMeta']['0'] = "メタデータの表示";
$GLOBALS['TL_LANG']['tl_content']['downloadShowMeta']['1'] = "アップロードの日付とファイルの大きさを表示しますか?";
$GLOBALS['TL_LANG']['tl_content']['downloadHideDate']['0'] = "アップロードの日付を表示しない";
$GLOBALS['TL_LANG']['tl_content']['downloadHideDate']['1'] = "アップロードの日付を表示しません。";
$GLOBALS['TL_LANG']['tl_content']['downloadNumberOfItems']['0'] = "ファイルの数の合計";
$GLOBALS['TL_LANG']['tl_content']['downloadNumberOfItems']['1'] = "ファイルの数の合計を制限できます。0にするとすべて表示します。";
$GLOBALS['TL_LANG']['tl_content']['downloadarchivSortingOptions']['sorting ASC'] = "昇順に並べ替え";
$GLOBALS['TL_LANG']['tl_content']['downloadarchivSortingOptions']['sorting DESC'] = "降順に並べ替え";
$GLOBALS['TL_LANG']['tl_content']['downloadarchivSortingOptions']['title ASC'] = "題名を昇順";
$GLOBALS['TL_LANG']['tl_content']['downloadarchivSortingOptions']['title DESC'] = "題名を降順";
$GLOBALS['TL_LANG']['tl_content']['downloadarchivSortingOptions']['tstamp ASC'] = "アップロード日を昇順";
$GLOBALS['TL_LANG']['tl_content']['downloadarchivSortingOptions']['tstamp DESC'] = "アップロード日を降順";
$GLOBALS['TL_LANG']['tl_content']['downloadmeta_legend'] = "メタデータ";
$GLOBALS['TL_LANG']['tl_content']['downloadarchive_legend'] = "ダウンロードアーカイブ";
 
?>
