<?php
/**
 * TL_ROOT/system/modules/downloadarchive/languages/ja/tl_downloadarchiveitems.php 
 * 
 * Contao extension: downloadarchive 2.0.0 stable 
 * Japanese translation file 
 * 
 * Copyright : &copy; 2008 - 2012 Felix Pfeiffer - Neue Medien 
 * License   : LGPL 
 * Author    : Felix Pfeiffer (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['title']['0'] = "題名";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['title']['1'] = "題名はダウンロードのリンクのテキストに表示します。理想的には短くて簡潔に説明するテキストとすべきです。<br />(例: \"製品番号1の価格\")";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['description']['0'] = "説明";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['description']['1'] = "ファイルの詳細な情報の説明を使用してください。この情報は、使用するテンプレートに依存して、一致したファイルに表示されます。";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['singleSRC']['0'] = "ファイル";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['singleSRC']['1'] = "ダウンロード対象にしたいファイルを選択してください。";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['protected']['0'] = "ファイルの保護";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['protected']['1'] = "特定のメンバーグループにだけファイルを表示します。";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['guests']['0'] = "ゲストだけに表示";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['guests']['1'] = "グインしているユーザーにファイルを表示しません。";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['groups']['0'] = "許可するメンバーグループ";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['groups']['1'] = "ファイルをダウンロードできるグループを選択します。";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['addImage']['0'] = "画像を追加";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['addImage']['1'] = "これを選択すると、画像をアーカイブのファイルに追加します。";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['useImage']['0'] = "画像のリンク";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['useImage']['1'] = "画像のリンクを使用しますか?";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['published']['0'] = "公開";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['published']['1'] = "これを選択するとファイルはをウェブサイトに表示します。";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['start']['0'] = "表示の開始";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['start']['1'] = "この日より前はダウンロードアーカイブをウェブサイトに表示しません。";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['stop']['0'] = "表示の終了";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['stop']['1'] = "この日から後はダウンロードアーカイブをウェブサイトに表示しません。";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['deleteConfirm'] = "ID %sのファイルをダウンロードアーカイブから本当に削除しますか?\n(ファイルそのものはサーバーから<strong>削除しません</strong>。)";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['useImageReference']['0'] = "なし";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['useImageReference']['1'] = "フルサイズ";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['useImageReference']['2'] = "ダウンロードのリンク";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['new']['0'] = "新しいファイル";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['new']['1'] = "ファイルを新しく作成";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['edit']['0'] = "ファイルの変更";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['edit']['1'] = "ID %sのファイルを変更";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['copy']['0'] = "ファイルを複製";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['copy']['1'] = "ID %sのファイルの複製";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['delete']['0'] = "ファイルを削除";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['delete']['1'] = "ID %sのファイルを削除";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['toggle']['0'] = "ファイルの公開と非公開を切り替え";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['toggle']['1'] = "ID %sのファイルの公開と非公開を切り替え";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['show']['0'] = "ファイルの詳細";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['show']['1'] = "ID %sのファイルのファイルの詳細を表示";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['title_legend'] = "題名と説明";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['file_legend'] = "ファイル";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['image_legend'] = "画像の使用";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['protection_legend'] = "ファイルの保護";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['publish_legend'] = "公開の設定";
 
?>
