<?php
/**
 * TL_ROOT/system/modules/downloadarchive/languages/ja/tl_downloadarchive.php 
 * 
 * Contao extension: downloadarchive 2.0.0 stable 
 * Japanese translation file 
 * 
 * Copyright : &copy; 2008 - 2012 Felix Pfeiffer - Neue Medien 
 * License   : LGPL 
 * Author    : Felix Pfeiffer (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_downloadarchive']['title']['0'] = "名前";
$GLOBALS['TL_LANG']['tl_downloadarchive']['title']['1'] = "ダウンロードアーカイブの名前を入力してください。この名前はバックエンドだけで表示されます。";
$GLOBALS['TL_LANG']['tl_downloadarchive']['showMeta']['0'] = "メタデータの表示";
$GLOBALS['TL_LANG']['tl_downloadarchive']['showMeta']['1'] = "各項目のアップロードの日付とファイルの大きさを表示しますか?";
$GLOBALS['TL_LANG']['tl_downloadarchive']['loadDirectory']['0'] = "ディレクトリの読み込み";
$GLOBALS['TL_LANG']['tl_downloadarchive']['loadDirectory']['1'] = "選択したディレクトリの内部のすべてのファイルを追加できます。このダウンロードアーカイブがファイルを含んでいない場合だけ、この設定を使用できます。";
$GLOBALS['TL_LANG']['tl_downloadarchive']['loadSubdir']['0'] = "サブディレクトリの取り込み";
$GLOBALS['TL_LANG']['tl_downloadarchive']['loadSubdir']['1'] = "すべてのサブディレクトリを調べてファイルを取り込みますか?";
$GLOBALS['TL_LANG']['tl_downloadarchive']['dirSRC']['0'] = "ディレクトリの選択";
$GLOBALS['TL_LANG']['tl_downloadarchive']['dirSRC']['1'] = "ファイルを取り込むディレクトリを選択してください。";
$GLOBALS['TL_LANG']['tl_downloadarchive']['prefix']['0'] = "名前に接頭文字列を使用";
$GLOBALS['TL_LANG']['tl_downloadarchive']['prefix']['1'] = "この窃盗文字列と増やしていく数値を使用して、それぞれのダウンロードの項目の題名を自動生成できます。(例: \"製品番号 0001\")";
$GLOBALS['TL_LANG']['tl_downloadarchive']['extension']['0'] = "拡張子";
$GLOBALS['TL_LANG']['tl_downloadarchive']['extension']['1'] = "特定のファイルの拡張子に限定できます。追加したいファイルの拡張子のコンマで区切ったリストを入力してください。";
$GLOBALS['TL_LANG']['tl_downloadarchive']['publishAll']['0'] = "すべてのファイルを自動的に公開";
$GLOBALS['TL_LANG']['tl_downloadarchive']['publishAll']['1'] = "フォルダーから取り込んだときに、すべてのファイルを公開します。";
$GLOBALS['TL_LANG']['tl_downloadarchive']['class']['0'] = "CSSのclass";
$GLOBALS['TL_LANG']['tl_downloadarchive']['class']['1'] = "このアーカイブのスタイルシートのclassを追加できます。このclassはすべてのファイルに設定されます。";
$GLOBALS['TL_LANG']['tl_downloadarchive']['published']['0'] = "公開";
$GLOBALS['TL_LANG']['tl_downloadarchive']['published']['1'] = "このオプションを選択しない限り、ウェブサイトにダウンロードアーカイブを表示しません。";
$GLOBALS['TL_LANG']['tl_downloadarchive']['start']['0'] = "表示の開始";
$GLOBALS['TL_LANG']['tl_downloadarchive']['start']['1'] = "この日より前はダウンロードアーカイブをウェブサイトに表示しません。";
$GLOBALS['TL_LANG']['tl_downloadarchive']['stop']['0'] = "表示の終了";
$GLOBALS['TL_LANG']['tl_downloadarchive']['stop']['1'] = "この日から後はダウンロードアーカイブをウェブサイトに表示しません。";
$GLOBALS['TL_LANG']['tl_downloadarchive']['deleteConfirm'] = "ID %?のダウンロードアーカイブを本当に削除しますか?<br/>(ファイルそのものはサーバーから<strong>削除されません</strong>。)";
$GLOBALS['TL_LANG']['tl_downloadarchive']['new']['0'] = "新しいアーカイブ";
$GLOBALS['TL_LANG']['tl_downloadarchive']['new']['1'] = "新しくダウンロードアーカイブを作成";
$GLOBALS['TL_LANG']['tl_downloadarchive']['edit']['0'] = "アーカイブを変更";
$GLOBALS['TL_LANG']['tl_downloadarchive']['edit']['1'] = "ID %sのアーカイブを変更";
$GLOBALS['TL_LANG']['tl_downloadarchive']['copy']['0'] = "アーカイブを複製";
$GLOBALS['TL_LANG']['tl_downloadarchive']['copy']['1'] = "ID %sのアーカイブを複製";
$GLOBALS['TL_LANG']['tl_downloadarchive']['delete']['0'] = "アーカイブを削除";
$GLOBALS['TL_LANG']['tl_downloadarchive']['delete']['1'] = "ID %sのアーカイブを削除";
$GLOBALS['TL_LANG']['tl_downloadarchive']['show']['0'] = "詳細を表示";
$GLOBALS['TL_LANG']['tl_downloadarchive']['show']['1'] = "ID %sのアーカイブの詳細を表示";
$GLOBALS['TL_LANG']['tl_downloadarchive']['title_legend'] = "題名";
$GLOBALS['TL_LANG']['tl_downloadarchive']['directory_legend'] = "フォルダーの読み込み";
 
?>
