<?php
/**
 * TL_ROOT/system/modules/downloadarchive/languages/ru/default.php 
 * 
 * Contao extension: downloadarchive 1.0.0 stable 
 * Russian translation file 
 * 
 * Copyright : &copy; 2008 Felix Pfeiffer - Neue Medien 
 * License   : LGPL 
 * Author    : Felix Pfeiffer (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Dmitri Kuznetsov (kuzmich), http://www.onfreedom.ru 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['keinDownload'] = "Файлы не найдены";
$GLOBALS['TL_LANG']['CTE']['downloadarchiv']['0'] = "Архив загрузок";
$GLOBALS['TL_LANG']['CTE']['downloadarchiv']['1'] = "Выберите архив загрузок как элемент контента.";
 
?>
