<?php
/**
 * TL_ROOT/system/modules/downloadarchive/languages/ru/modules.php 
 * 
 * Contao extension: downloadarchive 1.0.0 stable 
 * Russian translation file 
 * 
 * Copyright : &copy; 2008 Felix Pfeiffer - Neue Medien 
 * License   : LGPL 
 * Author    : Felix Pfeiffer (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Dmitri Kuznetsov (kuzmich), http://www.onfreedom.ru 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['downloadarchiv']['0'] = "Архив загрузок";
$GLOBALS['TL_LANG']['MOD']['downloadarchiv']['1'] = "Архив загрузок позволяет загружать файлы из одной или нескольких папок, а также указывать файлам выборочное название или описание, независимо от meta.txt. Кроме того, вы можете установить правила авторизации для каждого файла.";
$GLOBALS['TL_LANG']['FMD']['downloadarchiv']['0'] = "Архив загрузок";
$GLOBALS['TL_LANG']['FMD']['downloadarchiv']['1'] = "Этот модуль предоставляет файлы архива загрузок.";
 
?>
