<?php
/**
 * TL_ROOT/system/modules/downloadarchive/languages/ru/tl_content.php 
 * 
 * Contao extension: downloadarchive 1.0.0 stable 
 * Russian translation file 
 * 
 * Copyright : &copy; 2008 Felix Pfeiffer - Neue Medien 
 * License   : LGPL 
 * Author    : Felix Pfeiffer (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Dmitri Kuznetsov (kuzmich), http://www.onfreedom.ru 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['downloadarchiv']['0'] = "Архив загрузок";
$GLOBALS['TL_LANG']['tl_content']['downloadarchiv']['1'] = "Выберите архив загрузок";
$GLOBALS['TL_LANG']['tl_content']['downloadShowMeta']['0'] = "Показать мета-данные";
$GLOBALS['TL_LANG']['tl_content']['downloadShowMeta']['1'] = "Хотите показать время загрузки и размер файла?";
$GLOBALS['TL_LANG']['tl_content']['downloadHideDate']['0'] = "Скрыть дату размещения";
$GLOBALS['TL_LANG']['tl_content']['downloadHideDate']['1'] = "Скрыть дату размещения на сервере";
$GLOBALS['TL_LANG']['tl_content']['downloadNumberOfItems']['0'] = "Общее количество файлов";
$GLOBALS['TL_LANG']['tl_content']['downloadNumberOfItems']['1'] = "Здесь вы можете ограничить общее количество файлов. Установите в 0, чтобы показать все.";
$GLOBALS['TL_LANG']['tl_content']['downloadarchivSortingOptions']['sorting ASC'] = "Сортировка по возрастанию";
$GLOBALS['TL_LANG']['tl_content']['downloadarchivSortingOptions']['sorting DESC'] = "Сортировка по убыванию";
$GLOBALS['TL_LANG']['tl_content']['downloadarchivSortingOptions']['title ASC'] = "Названия по возрастанию";
$GLOBALS['TL_LANG']['tl_content']['downloadarchivSortingOptions']['title DESC'] = "Названия по убыванию";
$GLOBALS['TL_LANG']['tl_content']['downloadarchivSortingOptions']['tstamp ASC'] = "Дата размещения по возрастанию";
$GLOBALS['TL_LANG']['tl_content']['downloadarchivSortingOptions']['tstamp DESC'] = "Дата размещения по убыванию";
$GLOBALS['TL_LANG']['tl_content']['downloadmeta_legend'] = "Мета-данные";
$GLOBALS['TL_LANG']['tl_content']['downloadarchive_legend'] = "Архив загрузок";
 
?>
