<?php
/**
 * TL_ROOT/system/modules/downloadarchive/languages/ru/tl_downloadarchiveitems.php 
 * 
 * Contao extension: downloadarchive 1.0.0 stable 
 * Russian translation file 
 * 
 * Copyright : &copy; 2008 Felix Pfeiffer - Neue Medien 
 * License   : LGPL 
 * Author    : Felix Pfeiffer (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Dmitri Kuznetsov (kuzmich), http://www.onfreedom.ru 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['title']['0'] = "Название";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['title']['1'] = "Заголовок будет отображаться как текст ссылки загрузки. В идеале это должны быть краткие текстовые описания. <br />(напр. \"Прайс продукции № 1\")";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['description']['0'] = "Описание";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['description']['1'] = "Используйте описание, что бы дать подробную информацию о файле. Эта информация будет отображаться с соответствующим файлом, в зависимости от используемого вами шаблона.";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['singleSRC']['0'] = "Файл";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['singleSRC']['1'] = "Выберите файл, который должен быть загружен.";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['protected']['0'] = "Защита файла";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['protected']['1'] = "Показать файл, только для определенных групп.";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['guests']['0'] = "Показывать только гостям";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['guests']['1'] = "Скрыть файл, если пользователь авторизовался на сайте.";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['groups']['0'] = "Разрешено членам групп";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['groups']['1'] = "Здесь вы можете выбрать, какие группы будут иметь возможность загружать файл.";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['addImage']['0'] = "Добавить изображение";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['addImage']['1'] = "Если вы выберете эту опцию, изображение будет добавлено к новости статьи.";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['useImage']['0'] = "Ссылка изображения";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['useImage']['1'] = "Хотите использовать ссылку на изображение?";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['published']['0'] = "Опубликовать";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['published']['1'] = "До тех пор, пока вы не отметите этот пункт, файл не будет виден посетителям сайта.";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['deleteConfirm'] = "Вы действительно хотите удалить файл с ID% из архива загрузок?\n(Файл не будет удален с сервера!";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['useImageReference']['0'] = "Нет";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['useImageReference']['1'] = "Полный размер";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['useImageReference']['2'] = "Ссылка загрузки";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['new']['0'] = "Новый файл";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['new']['1'] = "Создать новый файл";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['edit']['0'] = "Редактировать файл";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['edit']['1'] = "Редактировать файл ID %s";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['copy']['0'] = "Копировать файл";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['copy']['1'] = "Копировать файл ID %s";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['delete']['0'] = "Удалить файл";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['delete']['1'] = "Удалить файл ID %s";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['show']['0'] = "Детали файла";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['show']['1'] = "Показать детали файла ID %s";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['title_legend'] = "Название и описание";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['file_legend'] = "Файл";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['image_legend'] = "Использовать изображение";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['protection_legend'] = "Защита файла";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['publish_legend'] = "Публикация";
 
?>
