<?php
/**
 * TL_ROOT/system/modules/downloadarchive/languages/fr/default.php 
 * 
 * TYPOlight extension: downloadarchive 0.5.1 stable 
 * French translation file 
 * 
 * Copyright : &copy; 2008 Felix Pfeiffer - Neue Medien 
 * License   : LGPL 
 * Author    : Felix Pfeiffer (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Guéric Folliot (gueric), http://www.typolight.fr 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['keinDownload'] = "Aucun fichier trouvé";
$GLOBALS['TL_LANG']['CTE']['downloadarchiv']['0'] = "Archive à télécharger";
$GLOBALS['TL_LANG']['CTE']['downloadarchiv']['1'] = "Sélectionner une archive à télécharger comme élément de contenu.";
 
?>
