<?php
/**
 * TL_ROOT/system/modules/downloadarchive/languages/fr/modules.php 
 * 
 * TYPOlight extension: downloadarchive 0.5.1 stable 
 * French translation file 
 * 
 * Copyright : &copy; 2008 Felix Pfeiffer - Neue Medien 
 * License   : LGPL 
 * Author    : Felix Pfeiffer (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Guéric Folliot (gueric), http://www.typolight.fr 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['downloadarchiv']['0'] = "Archive à télécharger";
$GLOBALS['TL_LANG']['MOD']['downloadarchiv']['1'] = "Une archive à télécharger permet le téléchargement de fichiers depuis un ou plusieurs dossiers et attibue à chaque fichier un titre et une description propre, indifféremment du fichier meta.txt. En outre, vous pouvez gérer les droits de téléchargement de chaque fichier.";
$GLOBALS['TL_LANG']['FMD']['downloadarchiv']['0'] = "Archive à télécharger";
$GLOBALS['TL_LANG']['FMD']['downloadarchiv']['1'] = "Ce module fournit les fichiers d'une archive à télécharger.";
 
?>
