<?php
/**
 * TL_ROOT/system/modules/downloadarchive/languages/fr/tl_downloadarchiveitems.php 
 * 
 * TYPOlight extension: downloadarchive 0.5.1 stable 
 * French translation file 
 * 
 * Copyright : &copy; 2008 Felix Pfeiffer - Neue Medien 
 * License   : LGPL 
 * Author    : Felix Pfeiffer (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Guéric Folliot (gueric), http://www.typolight.fr 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['title']['0'] = "Titre";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['title']['1'] = "Le titre sera affiché comme texte du lien de téléchargement. Il devrait idéalement donner une courte et précise description du fichier.<br />(ex: \"fiche produit 1\")";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['description']['0'] = "Description";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['description']['1'] = "Utilisez la description pour donner des informations détaillées sur le fichier. Cette information sera affichée avec le fichier correspondant, selon le modèle que vous utilisez.";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['singleSRC']['0'] = "Fichier";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['singleSRC']['1'] = "Sélectionnez le fichier qui sera téléchargeable.";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['protected']['0'] = "Protéger le fichier";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['protected']['1'] = "Afficher le fichier à certains groupes de membres seulement.";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['guests']['0'] = "Afficher aux invités seulement";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['guests']['1'] = "Cacher le fichier, à moins qu'un membre soit loggué.";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['groups']['0'] = "Groupes de membres autorisés";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['groups']['1'] = "Ici vous pouvez choisir quels groupes seront autorisés à télécharger le fichier.";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['addImage']['0'] = "Ajouter une image";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['addImage']['1'] = "Si vous choisissez cette option, une image sera ajoutée au fichier à télécharger.";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['useImage']['0'] = "Lien de l'image";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['useImage']['1'] = "Voulez vous ajouter un lien sur l'image?";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['deleteConfirm'] = "Voulez vous vraiment supprimer le fichier dont l'ID est %s de l'archive à télécharger?\n(Le fichier NE SERA PAS supprimé du serveur)";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['useImageReference']['0'] = "aucune";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['useImageReference']['1'] = "taille normale";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['useImageReference']['2'] = "lien de téléchargement";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['new']['0'] = "Nouveau fichier";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['new']['1'] = "Créer un nouveau fichier";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['edit']['0'] = "Modifier le fichier";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['edit']['1'] = "Modifier le fichier dont l'ID est %s";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['copy']['0'] = "Copier le fichier";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['copy']['1'] = "Copier le fichier dont l'ID est %s";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['delete']['0'] = "Supprimer le fichier";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['delete']['1'] = "Supprimer le fichier dont l'ID est %s";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['show']['0'] = "Détails du fichier";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['show']['1'] = "Afficher les détails du fichier dont l'ID est %s";
 
?>
