<?php
/**
 * TL_ROOT/system/modules/downloadarchive/languages/fa/tl_content.php 
 * 
 * Contao extension: downloadarchive 1.0.0 stable 
 * Persian translation file 
 * 
 * Copyright : &copy; 2008 Felix Pfeiffer - Neue Medien 
 * License   : LGPL 
 * Author    : Felix Pfeiffer (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Hamid Abbaszadeh (respinar), http://www.contao.ir/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['downloadarchiv']['0'] = "آرشیو دانلود";
$GLOBALS['TL_LANG']['tl_content']['downloadarchiv']['1'] = "یک آرشیو دانلود انتخاب نمایید.";
$GLOBALS['TL_LANG']['tl_content']['downloadShowMeta']['0'] = "نمایش metadata?";
$GLOBALS['TL_LANG']['tl_content']['downloadHideDate']['0'] = "مخفی کردن تاریخ بارگذاری";
$GLOBALS['TL_LANG']['tl_content']['downloadHideDate']['1'] = "تاریخ بارگذاری مخفی خواهد بود.";
$GLOBALS['TL_LANG']['tl_content']['downloadNumberOfItems']['0'] = "کل تعداد فایل‌ها";
$GLOBALS['TL_LANG']['tl_content']['downloadarchivSortingOptions']['sorting ASC'] = "ترتیب صعودی";
$GLOBALS['TL_LANG']['tl_content']['downloadarchivSortingOptions']['sorting DESC'] = "ترتیب نزولی";
$GLOBALS['TL_LANG']['tl_content']['downloadarchivSortingOptions']['title ASC'] = "عنوان صعودی";
$GLOBALS['TL_LANG']['tl_content']['downloadarchivSortingOptions']['title DESC'] = "عنوان نزولی";
$GLOBALS['TL_LANG']['tl_content']['downloadarchivSortingOptions']['tstamp ASC'] = "تاریخ بارگذاری صعودی";
$GLOBALS['TL_LANG']['tl_content']['downloadarchivSortingOptions']['tstamp DESC'] = "تاریخ بارگذاری نزولی";
$GLOBALS['TL_LANG']['tl_content']['downloadmeta_legend'] = "Meta data";
$GLOBALS['TL_LANG']['tl_content']['downloadarchive_legend'] = "Downloadarchive";
 
?>
