<?php
/**
 * TL_ROOT/system/modules/downloadarchive/languages/fa/tl_downloadarchive.php 
 * 
 * Contao extension: downloadarchive 1.0.0 stable 
 * Persian translation file 
 * 
 * Copyright : &copy; 2008 Felix Pfeiffer - Neue Medien 
 * License   : LGPL 
 * Author    : Felix Pfeiffer (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Hamid Abbaszadeh (respinar), http://www.contao.ir/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_downloadarchive']['title']['0'] = "نام";
$GLOBALS['TL_LANG']['tl_downloadarchive']['extension']['0'] = "افزونه‌ها";
$GLOBALS['TL_LANG']['tl_downloadarchive']['class']['0'] = "کلاس CSS";
$GLOBALS['TL_LANG']['tl_downloadarchive']['new']['0'] = "آرشیو جدید";
$GLOBALS['TL_LANG']['tl_downloadarchive']['new']['1'] = "ایجاد یک آرشیو دانلود جدید.";
$GLOBALS['TL_LANG']['tl_downloadarchive']['edit']['0'] = "ویرایش آرشیو";
$GLOBALS['TL_LANG']['tl_downloadarchive']['edit']['1'] = "ویرایش آرشیو با شناسه %s";
$GLOBALS['TL_LANG']['tl_downloadarchive']['copy']['0'] = "کپی آرشیو";
$GLOBALS['TL_LANG']['tl_downloadarchive']['copy']['1'] = "کپی آرشیو با شناسه %s";
$GLOBALS['TL_LANG']['tl_downloadarchive']['delete']['0'] = "حذف آرشیو";
$GLOBALS['TL_LANG']['tl_downloadarchive']['delete']['1'] = "حذف آرشیو با شناسه %s";
$GLOBALS['TL_LANG']['tl_downloadarchive']['show']['0'] = "مشاهده جزئیات";
 
?>
