<?php
/**
 * TL_ROOT/system/modules/downloadarchive/languages/fa/tl_downloadarchiveitems.php 
 * 
 * Contao extension: downloadarchive 1.0.0 stable 
 * Persian translation file 
 * 
 * Copyright : &copy; 2008 Felix Pfeiffer - Neue Medien 
 * License   : LGPL 
 * Author    : Felix Pfeiffer (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Hamid Abbaszadeh (respinar), http://www.contao.ir/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['title']['0'] = "عنوان";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['description']['0'] = "توضیح";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['singleSRC']['0'] = "فایل";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['protected']['0'] = "حفاظا از فایل";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['file_legend'] = "فابل";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['image_legend'] = "استفاده از تصویر";
 
?>
