<?php
/**
 * TL_ROOT/system/modules/downloadarchive/languages/fa/tl_module.php 
 * 
 * Contao extension: downloadarchive 1.0.0 stable 
 * Persian translation file 
 * 
 * Copyright : &copy; 2008 Felix Pfeiffer - Neue Medien 
 * License   : LGPL 
 * Author    : Felix Pfeiffer (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Hamid Abbaszadeh (respinar), http://www.contao.ir/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['downloadmeta_legend'] = "Meta data";
$GLOBALS['TL_LANG']['tl_module']['downloadarchive_legend'] = "Downloadarchive";
 
?>
