<?php
/**
 * TL_ROOT/system/modules/downloadarchive/languages/it/default.php 
 * 
 * TYPOlight extension: downloadarchive 1.0.0 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; 2008 Felix Pfeiffer - Neue Medien 
 * License   : LGPL 
 * Author    : Felix Pfeiffer (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Paolo Brunelli (PaoloB), http://www.typolightcms.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['keinDownload'] = "Nessun file trovato";
$GLOBALS['TL_LANG']['CTE']['downloadarchiv']['0'] = "Archivio Download";
$GLOBALS['TL_LANG']['CTE']['downloadarchiv']['1'] = "Inserisci un archivio per download come contenuto";
 
?>
