<?php
/**
 * TL_ROOT/system/modules/downloadarchive/languages/it/modules.php 
 * 
 * TYPOlight extension: downloadarchive 1.0.0 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; 2008 Felix Pfeiffer - Neue Medien 
 * License   : LGPL 
 * Author    : Felix Pfeiffer (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Paolo Brunelli (PaoloB), http://www.typolightcms.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['downloadarchiv']['0'] = "Archivio Download";
$GLOBALS['TL_LANG']['MOD']['downloadarchiv']['1'] = "Un archivio per download permette di scaricare file da una o più cartelle, nonchè di fornire ogni file con un titolo e una descrizione corretta. In aggiunta, è possibile attivare i permessi del download per ogni file.";
$GLOBALS['TL_LANG']['FMD']['downloadarchiv']['0'] = "Archivio Download";
$GLOBALS['TL_LANG']['FMD']['downloadarchiv']['1'] = "Questo modulo permette di pubblicare i file di un archivio per download";
 
?>
