<?php
/**
 * TL_ROOT/system/modules/downloadarchive/languages/it/tl_content.php 
 * 
 * TYPOlight extension: downloadarchive 1.0.0 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; 2008 Felix Pfeiffer - Neue Medien 
 * License   : LGPL 
 * Author    : Felix Pfeiffer (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Paolo Brunelli (PaoloB), http://www.typolightcms.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['downloadarchiv']['0'] = "Archivio Download";
$GLOBALS['TL_LANG']['tl_content']['downloadarchiv']['1'] = "Seleziona un archivio per il download";
$GLOBALS['TL_LANG']['tl_content']['downloadShowMeta']['0'] = "Vuoi visualizzare i meta data?";
$GLOBALS['TL_LANG']['tl_content']['downloadShowMeta']['1'] = "Vuoi mostrare il tempo di caricamento e la dimensione del file?";
$GLOBALS['TL_LANG']['tl_content']['downloadHideDate']['0'] = "Nascondi la data di caricamento";
$GLOBALS['TL_LANG']['tl_content']['downloadHideDate']['1'] = "La data di caricamento sarà nascosta";
$GLOBALS['TL_LANG']['tl_content']['downloadNumberOfItems']['0'] = "Numero totale file";
$GLOBALS['TL_LANG']['tl_content']['downloadNumberOfItems']['1'] = "Qui si può limitare il numero totale di file. Impostato a 0 per mostrarli tutti.";
$GLOBALS['TL_LANG']['tl_content']['downloadarchivSortingOptions']['sorting ASC'] = "Ordinamento crescente";
$GLOBALS['TL_LANG']['tl_content']['downloadarchivSortingOptions']['sorting DESC'] = "Ordinamento decrescente";
$GLOBALS['TL_LANG']['tl_content']['downloadarchivSortingOptions']['title ASC'] = "Titolo crescente";
$GLOBALS['TL_LANG']['tl_content']['downloadarchivSortingOptions']['title DESC'] = "Titolo decrescente";
$GLOBALS['TL_LANG']['tl_content']['downloadarchivSortingOptions']['tstamp ASC'] = "Data di caricamento crescente";
$GLOBALS['TL_LANG']['tl_content']['downloadarchivSortingOptions']['tstamp DESC'] = "Data di caricamento decrescente";
$GLOBALS['TL_LANG']['tl_content']['downloadmeta_legend'] = "Meta data";
$GLOBALS['TL_LANG']['tl_content']['downloadarchive_legend'] = "Archivio Download";
 
?>
