<?php
/**
 * TL_ROOT/system/modules/downloadarchive/languages/it/tl_downloadarchive.php 
 * 
 * TYPOlight extension: downloadarchive 1.0.0 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; 2008 Felix Pfeiffer - Neue Medien 
 * License   : LGPL 
 * Author    : Felix Pfeiffer (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Paolo Brunelli (PaoloB), http://www.typolightcms.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_downloadarchive']['title']['0'] = "Titolo";
$GLOBALS['TL_LANG']['tl_downloadarchive']['title']['1'] = "Inserire un nome per l'archivio. Questo nome verrà visualizzato solo nel backend.";
$GLOBALS['TL_LANG']['tl_downloadarchive']['showMeta']['0'] = "Vuoi visualizzare i meta data?";
$GLOBALS['TL_LANG']['tl_downloadarchive']['showMeta']['1'] = "Vuoi mostrare la data di caricamento e le dimensioni del file per ogni elemento?";
$GLOBALS['TL_LANG']['tl_downloadarchive']['loadDirectory']['0'] = "Vuoi scansionare una cartella?";
$GLOBALS['TL_LANG']['tl_downloadarchive']['loadDirectory']['1'] = "E' possibile aggiungere tutti i file presenti all'interno della cartella scelta. Questo opzione funziona solo se non sono stati selezionati file a questo archivio di download.";
$GLOBALS['TL_LANG']['tl_downloadarchive']['loadSubdir']['0'] = "Vuoi scansionare le sottocartelle?";
$GLOBALS['TL_LANG']['tl_downloadarchive']['loadSubdir']['1'] = "Vuoi scansionare tutte le sottocartelle?";
$GLOBALS['TL_LANG']['tl_downloadarchive']['dirSRC']['0'] = "Seleziona una cartella";
$GLOBALS['TL_LANG']['tl_downloadarchive']['dirSRC']['1'] = "Selezionare la cartella che si desidera sottoporre a scansione";
$GLOBALS['TL_LANG']['tl_downloadarchive']['prefix']['0'] = "Usa un prefisso";
$GLOBALS['TL_LANG']['tl_downloadarchive']['prefix']['1'] = "E' possibile generare automaticamente il titolo per ciascun file da scaricare utilizzando questa stringa prefisso e un numero incrementale (Esempio: \"I nostri prodotti 0001\")";
$GLOBALS['TL_LANG']['tl_downloadarchive']['extension']['0'] = "Estensioni";
$GLOBALS['TL_LANG']['tl_downloadarchive']['extension']['1'] = "E' possibile limitare la scansione ad alcune estensioni di file. Si prega di inserire un elenco di estensioni che si desidera aggiungere separato da virgole";
$GLOBALS['TL_LANG']['tl_downloadarchive']['publishAll']['0'] = "Pubblica automaticamente tutti i file";
$GLOBALS['TL_LANG']['tl_downloadarchive']['publishAll']['1'] = "Selezionare questa opzione per pubblicare tutti i file quando si importa la cartella";
$GLOBALS['TL_LANG']['tl_downloadarchive']['class']['0'] = "Classe CSS";
$GLOBALS['TL_LANG']['tl_downloadarchive']['class']['1'] = "E' possibile aggiungere una classe CSS per l'archivio. Questa classe sarà utilizzata per ogni file.";
$GLOBALS['TL_LANG']['tl_downloadarchive']['deleteConfirm'] = "Vuoi cancellare il record ID%?\n(I file non saranno cancellati dal server)";
$GLOBALS['TL_LANG']['tl_downloadarchive']['new']['0'] = "Nuovo archivio";
$GLOBALS['TL_LANG']['tl_downloadarchive']['new']['1'] = "Crea un nuovo archivio";
$GLOBALS['TL_LANG']['tl_downloadarchive']['edit']['0'] = "Modifica archivio";
$GLOBALS['TL_LANG']['tl_downloadarchive']['edit']['1'] = "Modifica l'archivio con ID %s";
$GLOBALS['TL_LANG']['tl_downloadarchive']['copy']['0'] = "Copia archivio";
$GLOBALS['TL_LANG']['tl_downloadarchive']['copy']['1'] = "Copiare l'archivio con ID %s";
$GLOBALS['TL_LANG']['tl_downloadarchive']['delete']['0'] = "Cancella archivio";
$GLOBALS['TL_LANG']['tl_downloadarchive']['delete']['1'] = "Cancella l'archivio con ID %s";
$GLOBALS['TL_LANG']['tl_downloadarchive']['show']['0'] = "Visualizza dettagli";
$GLOBALS['TL_LANG']['tl_downloadarchive']['show']['1'] = "Visualizza i dettagli dell'archivio con ID %s";
$GLOBALS['TL_LANG']['tl_downloadarchive']['title_legend'] = "Titolo";
$GLOBALS['TL_LANG']['tl_downloadarchive']['directory_legend'] = "Leggi cartella";
 
?>
