<?php
/**
 * TL_ROOT/system/modules/downloadarchive/languages/it/tl_downloadarchiveitems.php 
 * 
 * TYPOlight extension: downloadarchive 1.0.0 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; 2008 Felix Pfeiffer - Neue Medien 
 * License   : LGPL 
 * Author    : Felix Pfeiffer (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Paolo Brunelli (PaoloB), http://www.typolightcms.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['title']['0'] = "Titolo";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['title']['1'] = "Il titolo verrà visualizzato come testo del link per il download. Dovresti fornire una descrizione breve e concisa del testo. <br /> ( \"Prodotto, ad esempio prezzo di no. 1\")";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['description']['0'] = "Descrizione";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['description']['1'] = "Utilizza la descrizione per fornire informazioni dettagliate sul file. Queste informazioni saranno visualizzate con il file corrispondente.";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['singleSRC']['0'] = "File";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['singleSRC']['1'] = "Seleziona il file che deve essere scaricato";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['protected']['0'] = "Proteggi file";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['protected']['1'] = "Selezionando questa opzione sarà possibile limitare l'accesso a determinati gruppi";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['guests']['0'] = "Mostra solo ai visitatori";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['guests']['1'] = "Nasconde il contenuto se un membro ha effettuato il login";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['groups']['0'] = "Accesso gruppi";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['groups']['1'] = "Selezionare i gruppi che potranno scaricare il file";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['addImage']['0'] = "Aggiungi immagine";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['addImage']['1'] = "Se si sceglie questa opzione sarà possibile aggiungere un'immagine all'archivio";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['useImage']['0'] = "Link all'immagine";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['useImage']['1'] = "Vuoi utilizzare un collegamento sull'immagine?";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['published']['0'] = "Pubblicato";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['published']['1'] = "Fin quando non si seleziona questa opzione la l'archivio non sarà visibile sul sito internet";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['deleteConfirm'] = "Vuoi davvero eliminare il file con ID %s da questo gruppo?\n(Il file non verrà eliminato dal server)";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['useImageReference']['0'] = "nessuna";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['useImageReference']['1'] = "Dimensioni originali";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['useImageReference']['2'] = "Link download";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['new']['0'] = "Nuovo file";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['new']['1'] = "Creare un nuovo file";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['edit']['0'] = "Modifica file";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['edit']['1'] = "Modificare il file ID %s";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['copy']['0'] = "Copia file";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['copy']['1'] = "Copiare il file ID %s";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['delete']['0'] = "Cancella file";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['delete']['1'] = "Cancellare il file ID %s";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['show']['0'] = "Dettagli file";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['show']['1'] = "Mostra i dettagli del file ID %s";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['title_legend'] = "Titolo e descrizione";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['file_legend'] = "File";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['image_legend'] = "Usa un'immagine";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['protection_legend'] = "Protezione accesso";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['publish_legend'] = "Impostazioni di pubblicazione";
 
?>
