<?php
/**
 * TL_ROOT/system/modules/downloadarchive/languages/cs/default.php 
 * 
 * Contao extension: downloadarchive 2.0.0 stable 
 * Czech translation file 
 * 
 * Copyright : &copy; 2008 - 2012 Felix Pfeiffer - Neue Medien 
 * License   : LGPL 
 * Author    : Felix Pfeiffer : Neue Medien (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['keinDownload'] = "Nebyly nalezeny žádné soubory";
$GLOBALS['TL_LANG']['CTE']['downloadarchiv']['0'] = "Download archiv";
$GLOBALS['TL_LANG']['CTE']['downloadarchiv']['1'] = "Vyberte download archiv jako prvek obsahu.";
 
?>
