<?php
/**
 * TL_ROOT/system/modules/downloadarchive/languages/cs/modules.php 
 * 
 * Contao extension: downloadarchive 2.0.0 stable 
 * Czech translation file 
 * 
 * Copyright : &copy; 2008 - 2012 Felix Pfeiffer - Neue Medien 
 * License   : LGPL 
 * Author    : Felix Pfeiffer : Neue Medien (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['downloadarchiv']['0'] = "Download archiv";
$GLOBALS['TL_LANG']['MOD']['downloadarchiv']['1'] = "Download archiv umožňuje stahovat soubory z jedné nebo více složek, jakož i poskytnout každému souboru vlastní název, popis a obrázek, bez ohledu na meta.txt. Kromě toho můžete nastavit parametry stahování pro každý jednotlivý soubor.";
$GLOBALS['TL_LANG']['FMD']['downloadarchive']['0'] = "Download archiv";
$GLOBALS['TL_LANG']['FMD']['downloadarchive']['1'] = "Tento modul poskytuje soubory pro stažení.";
 
?>
