<?php
/**
 * TL_ROOT/system/modules/downloadarchive/languages/cs/tl_downloadarchive.php 
 * 
 * Contao extension: downloadarchive 2.0.0 stable 
 * Czech translation file 
 * 
 * Copyright : &copy; 2008 - 2012 Felix Pfeiffer - Neue Medien 
 * License   : LGPL 
 * Author    : Felix Pfeiffer : Neue Medien (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_downloadarchive']['title']['0'] = "Název archivu";
$GLOBALS['TL_LANG']['tl_downloadarchive']['title']['1'] = "Zadejte název download archivu. Toto jméno bude zobrazeno pouze v backend.";
$GLOBALS['TL_LANG']['tl_downloadarchive']['showMeta']['0'] = "Zobrazit metadata?";
$GLOBALS['TL_LANG']['tl_downloadarchive']['showMeta']['1'] = "Chcete zobrazit datum uložení a velikost souboru pro každou položku?";
$GLOBALS['TL_LANG']['tl_downloadarchive']['loadDirectory']['0'] = "Prohlížet adresář?";
$GLOBALS['TL_LANG']['tl_downloadarchive']['loadDirectory']['1'] = "Můžete přidat všechny soubory uvnitř vybraného adresáře. Toto bude fungovat pouze v případě, že nejsou žádné soubory připojené k tomuto download archivu.";
$GLOBALS['TL_LANG']['tl_downloadarchive']['loadSubdir']['0'] = "Prohlížet podadresáře?";
$GLOBALS['TL_LANG']['tl_downloadarchive']['loadSubdir']['1'] = "Chcete prohlížet všechny podadresáře?";
$GLOBALS['TL_LANG']['tl_downloadarchive']['dirSRC']['0'] = "Vyberte adresář";
$GLOBALS['TL_LANG']['tl_downloadarchive']['dirSRC']['1'] = "Vyberte adresář, který chcete prohlížet.";
$GLOBALS['TL_LANG']['tl_downloadarchive']['prefix']['0'] = "Použít prefix";
$GLOBALS['TL_LANG']['tl_downloadarchive']['prefix']['1'] = "Můžete automaticky generovat název pro každý prvek ke stažení pomocí tohoto prefixu (Příklad: \"Naše výrobky 0001\").";
$GLOBALS['TL_LANG']['tl_downloadarchive']['extension']['0'] = "Rozšíření";
$GLOBALS['TL_LANG']['tl_downloadarchive']['extension']['1'] = "Můžete omezit prohlížení na přípony souborů. Zadejte prosím čárkou oddělený seznam přípon, které chcete přidat.";
$GLOBALS['TL_LANG']['tl_downloadarchive']['publishAll']['0'] = "Automaticky zveřejní všechny soubory";
$GLOBALS['TL_LANG']['tl_downloadarchive']['publishAll']['1'] = "Zaškrtněte tuto volbu, abyste zveřejnili všechny soubory, při importu složky.";
$GLOBALS['TL_LANG']['tl_downloadarchive']['class']['0'] = "CSS třída";
$GLOBALS['TL_LANG']['tl_downloadarchive']['class']['1'] = "Můžete přidat css třídu do archivu. Tato třída bude nastavena pro každý soubor.";
$GLOBALS['TL_LANG']['tl_downloadarchive']['published']['0'] = "Publikovat";
$GLOBALS['TL_LANG']['tl_downloadarchive']['published']['1'] = "Pokud zvolíte tuto možnost, archiv není viditelné pro návštěvníky webových stránek.";
$GLOBALS['TL_LANG']['tl_downloadarchive']['start']['0'] = "Zobrazit od";
$GLOBALS['TL_LANG']['tl_downloadarchive']['start']['1'] = "Nezobrazovat archiv na webových stránkách před tímto dnem.";
$GLOBALS['TL_LANG']['tl_downloadarchive']['stop']['0'] = "Zobrazit do";
$GLOBALS['TL_LANG']['tl_downloadarchive']['stop']['1'] = "Nezobrazovat archiv na webových stránkách na a po tomto dni.";
$GLOBALS['TL_LANG']['tl_downloadarchive']['deleteConfirm'] = "Opravdu chcete odstranit download archiv ID%s?\n(Soubory nebudou vymazány ze serveru)";
$GLOBALS['TL_LANG']['tl_downloadarchive']['new']['0'] = "Nový archiv";
$GLOBALS['TL_LANG']['tl_downloadarchive']['new']['1'] = "Vytvořit nový download archiv.";
$GLOBALS['TL_LANG']['tl_downloadarchive']['edit']['0'] = "Upravit archiv";
$GLOBALS['TL_LANG']['tl_downloadarchive']['edit']['1'] = "Upravit archiv ID %s.";
$GLOBALS['TL_LANG']['tl_downloadarchive']['copy']['0'] = "Kopírovat archiv";
$GLOBALS['TL_LANG']['tl_downloadarchive']['copy']['1'] = "Kopírovat archiv ID %s.";
$GLOBALS['TL_LANG']['tl_downloadarchive']['delete']['0'] = "Odstranit archiv";
$GLOBALS['TL_LANG']['tl_downloadarchive']['delete']['1'] = "Odstranit archiv ID %s.";
$GLOBALS['TL_LANG']['tl_downloadarchive']['show']['0'] = "Zobrazit podrobnosti";
$GLOBALS['TL_LANG']['tl_downloadarchive']['show']['1'] = "Zobrazit podrobnosti archivu ID %s.";
$GLOBALS['TL_LANG']['tl_downloadarchive']['title_legend'] = "Název";
$GLOBALS['TL_LANG']['tl_downloadarchive']['directory_legend'] = "Prohlížet složku";
 
?>
