<?php
/**
 * TL_ROOT/system/modules/downloadarchive/languages/cs/tl_downloadarchiveitems.php 
 * 
 * Contao extension: downloadarchive 2.0.0 stable 
 * Czech translation file 
 * 
 * Copyright : &copy; 2008 - 2012 Felix Pfeiffer - Neue Medien 
 * License   : LGPL 
 * Author    : Felix Pfeiffer : Neue Medien (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['title']['0'] = "Název";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['title']['1'] = "Název bude zobrazen jako odkaz ke stažení. Měl by být v ideálním případě stručný a výstižný.";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['description']['0'] = "Popis";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['description']['1'] = "Použijte popis pokud chcete poskytnout podrobné informace o souboru. Tyto informace se zobrazí s odpovídajícím souborem v závislosti na šabloně, kterou používáte.";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['singleSRC']['0'] = "Soubor";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['singleSRC']['1'] = "Vyberte soubor, který má být stažen.";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['protected']['0'] = "Chránit soubor";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['protected']['1'] = "Zobrazit soubor pouze pro určité členy skupiny.";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['guests']['0'] = "Zobrazit pouze hostům";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['guests']['1'] = "Skrýt soubor pokud je člen přihlášen.";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['groups']['0'] = "Povolené skupiny";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['groups']['1'] = "Zde si můžete vybrat, které skupiny budou moci stáhnout soubor.";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['addImage']['0'] = "Přidat obrázek";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['addImage']['1'] = "Pokud zvolíte tuto možnost, bude přidán obrazek.";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['useImage']['0'] = "Použít obrázek jako odkaz";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['useImage']['1'] = "Chcete použít obrázek jako odkaz?";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['published']['0'] = "Publikovat";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['published']['1'] = "Pokud nezvolíte tuto možnost, soubor nebude viditelný pro návštěvníky webových stránek.";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['start']['0'] = "Zobrazit od";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['start']['1'] = "Nezobrazovat soubor na webových stránkách před tímto dnem.";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['stop']['0'] = "Zobrazit do";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['stop']['1'] = "Nezobrazovat soubor na internetové stránky, na a po tomto dni.";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['deleteConfirm'] = "Opravdu chcete odstranit soubor ID %s z download archivu?\n(Soubor nebude odstraněn ze serveru)";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['useImageReference']['0'] = "žádný";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['useImageReference']['1'] = "V plné velikosti";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['useImageReference']['2'] = "Odkaz ke stažení";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['new']['0'] = "Nový soubor";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['new']['1'] = "Přidat nový soubor";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['edit']['0'] = "Upravit soubor";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['edit']['1'] = "Upravit soubor ID %s";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['copy']['0'] = "Kopírovat soubor";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['copy']['1'] = "Kopírovat soubor ID %s";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['delete']['0'] = "Odstranit soubor";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['delete']['1'] = "Odstranit soubor ID %s";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['toggle']['0'] = "Publikovat/nepublikovat soubor";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['toggle']['1'] = "Publikovat/nepublikovat soubor ID %s";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['show']['0'] = "Zobrazit podrobnosti";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['show']['1'] = "Zobrazit podrobnosti ID %s";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['title_legend'] = "Název a popis";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['file_legend'] = "Soubor";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['image_legend'] = "Použít obrázek";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['protection_legend'] = "Ochrana souboru";
$GLOBALS['TL_LANG']['tl_downloadarchiveitems']['publish_legend'] = "Publikovat";
 
?>
