<?php
/**
 * TL_ROOT/system/modules/downloadarchive/languages/cs/tl_module.php 
 * 
 * Contao extension: downloadarchive 2.0.0 stable 
 * Czech translation file 
 * 
 * Copyright : &copy; 2008 - 2012 Felix Pfeiffer - Neue Medien 
 * License   : LGPL 
 * Author    : Felix Pfeiffer : Neue Medien (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['downloadarchiv']['0'] = "Download archiv";
$GLOBALS['TL_LANG']['tl_module']['downloadarchiv']['1'] = "Vyberte prosím download archivu, který má být zobrazen v tomto modulu.";
$GLOBALS['TL_LANG']['tl_module']['downloadShowMeta']['0'] = "Zobrazit metadata?";
$GLOBALS['TL_LANG']['tl_module']['downloadShowMeta']['1'] = "Chcete zobrazit datum uložení a velikost souboru?";
$GLOBALS['TL_LANG']['tl_module']['downloadHideDate']['0'] = "Skrýt datum uložení";
$GLOBALS['TL_LANG']['tl_module']['downloadHideDate']['1'] = "Pokud vyberete tuto volbu, datum uložení na server bude skryto.";
$GLOBALS['TL_LANG']['tl_module']['downloadNumberOfItems']['0'] = "Celkový počet souborů";
$GLOBALS['TL_LANG']['tl_module']['downloadNumberOfItems']['1'] = "Zde můžete omezit celkový počet souborů. Nastavena 0 zobrazí všechny.";
$GLOBALS['TL_LANG']['tl_module']['downloadarchivSortingOptions']['sorting ASC'] = "Řadit vzestupně";
$GLOBALS['TL_LANG']['tl_module']['downloadarchivSortingOptions']['sorting DESC'] = "Řadit sestupně";
$GLOBALS['TL_LANG']['tl_module']['downloadarchivSortingOptions']['title ASC'] = "Název vzestupně";
$GLOBALS['TL_LANG']['tl_module']['downloadarchivSortingOptions']['title DESC'] = "Název sestupně";
$GLOBALS['TL_LANG']['tl_module']['downloadarchivSortingOptions']['tstamp ASC'] = "Datum uložení vzestupně";
$GLOBALS['TL_LANG']['tl_module']['downloadarchivSortingOptions']['tstamp DESC'] = "Datum uložení sestupně";
$GLOBALS['TL_LANG']['tl_module']['downloadmeta_legend'] = "Meta data";
$GLOBALS['TL_LANG']['tl_module']['downloadarchive_legend'] = "Download archiv";
 
?>
